# Generated by Django 3.0.7 on 2021-04-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210417_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='user',
            new_name='users',
        ),
    ]
