# Generated by Django 3.0.7 on 2021-04-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210417_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_group',
            new_name='user_as_group',
        ),
    ]
